name: invite_server_local

services:
  postgres:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/posgres:/var/lib/posgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=invite
  redis:
    image: redis:8.0-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
