name: invite_server 

services:
  api:
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/invite"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db 
      - redis 
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=invite
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

volumes:
  db:
    driver: local
  redis:
    driver: local