name: invite_server 

services:
  api:
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
      APP_CLERK_KEY: ${APP_CLERK_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db 
      - cache 
  db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
  cache:
    image: redis:8.0-alpine
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local