server:
  port: 8088
  hmac_secret: "uber_secret_here_replace_later"
database:
  host: "localhost"
  port: 5431
  name: "invite"
  username: "postgres"
  password: "password"
redis_url: "redis://127.0.0.1:6379"